name: Deploy to Aliyun ECS

on:
  push:
    branches:
      - master
  workflow_dispatch:  # 支持手动运行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install rsync
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ECS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.ECS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to ECS
        run: |
          # 使用 rsync 上传文件到 ECS 服务器的 www 目录，排除 .github 文件夹
          rsync -avz --delete --exclude='.github/' --exclude='.git/' -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.ECS_USER }}@${{ secrets.ECS_HOST }}:${{ secrets.ECS_TARGET_PATH }}/

      - name: Cleanup
        run: |
          rm -rf ~/.ssh/id_rsa
